#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
  path: /logout
  methods: GET

_errors:
  resource: '@TwigBundle/Resources/config/routing/errors.xml'
  prefix:   /_error
